# Site settings
title: 肖飞
subtitle: 
keywords: 肖飞
description: 家徒四壁 四海为家 唯有代码
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://et-stack.github.io/" # 你的域名
page_no_title: "肖飞's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: 肖飞
email: 1826869334@qq.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接



# Google Analytics
ga_track_id: 'UA-130856615-1'            # Format: UA-xxxxxx-xx
ga_domain: https://et-stack.github.io/           # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Code hub settings
codehub: # 代码仓库
  - title: GitHub
    url: https://github.com/et-stack


valine:
  enable: true
  app_id:  or60v4ihscOTk4oLIbEYzSv8-gzGzoHsz
  app_key: TRfR09vYeQ7hKWQbL2SOwPE6
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
  guest_info: nick,mail,link
  pageSize: 10
